### ISSUE TITLE
Bllipparser not included

### ISSUE THREAD

**Issue by ladyfrauke** [KantanLabs/KantanPreorder#1]
Hi, 

The readme says that the bllipparser is provided with this script, but in fact it isn't. I had to install it separately. In case I just got something wrong, maybe updating the readme would be possible, to prevent other poor souls encountering this error. 

System: Ubuntu 16.04 Server

Best regards
Frauke

**Comment by KantanLabs** [comment]
Dear Frauke, 

Thank you for your feed back and apologies for the inconvenience. 

The BLLIP parser is included now in the repository. 

Kind regards, 
Dimitar.
